### ISSUE TITLE
indentation errors

### ISSUE THREAD

**Issue by liklev** [torokj/Geometric_fragmentation#2]
Helló!
zipként letöltöttem a master foldert.
a randomcut1.py hőbörög a tabuláció miatt (a 34. sorral kezdi, utána is akadhat)

legjobbakat, levente

**Comment by torokj** [comment]
Megoldottam tab->8 space.

**Comment by liklev** [comment]
oké, kösz!
továbblépett, és nálam nem haverkodik a zárójelmentes print sorokkal
(python3 3.9-nél járok)
miután az összes print-et átbütyköltem print()-es syntax-ra már
elindul és eljutott az első üzenetig, ahol kiírja a usage formátumot
....N seed outpu.....

mivel kell etetni ?
a readme.md nem árul el róla sokat.

csóváz, levente

**Comment by torokj** [comment]
Kibővítettem a readme-t. Hát tudod, hogy van ez elfogadták a cikket, de express publikálni kell a kódot. Szépségre, használhatóságra nem jutott idő :-) Köszönöm az észrevételeket.

**Comment by liklev** [comment]
oké, megnézem mindjárt.

van egy csávó, adrian rossiter, iszonyat csomagot rakott össze antiprism néven.

https://www.antiprism.com/

mindenféle truncation-ökkel, meg tesselációkkal zúz, és azonnali 3D
viewere van, amiben meg lehet tekinteni a cuccakat.

és rettenet segítőkész srác

üdv, levi

**Comment by liklev** [comment]
ahhh...
némi próbálkozás után bejött, hogy csak 3 darab nyers számot vár paraméterként.

az outputtype = 0 szépen kiírja a terminálba az eredményt, csak az 1
(data) hová teszi?
(márha megnézném a "mozi"-val?)


a feljavított readme-be az eredménypéldád elé be lehetne szúrni magát
a parancsot, amire az eredmény kijött? (az ilyen kóklereknek, mint én)

üdv, levi
